/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.pkg3;
import java.util.ArrayList;
import static laboratorio.pkg3.ParkingParameters.Parking1;


/**
 *
 * @author User
 */
public class ParkingInterface extends javax.swing.JFrame {
    
    /**
     * Creates new form Prueba
     */
    public ParkingInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        consolidated = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CarsSpace = new javax.swing.JLabel();
        MotorcyclesSpace = new javax.swing.JLabel();
        BikesSpace = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(420, 265));
        setMinimumSize(new java.awt.Dimension(420, 265));
        setPreferredSize(new java.awt.Dimension(420, 265));
        getContentPane().setLayout(null);

        jButton1.setText("Ingreso de vehículo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(220, 30, 150, 25);

        jButton2.setText("Salida de vehículo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 70, 150, 25);

        consolidated.setText("Consolidado");
        consolidated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consolidatedActionPerformed(evt);
            }
        });
        getContentPane().add(consolidated);
        consolidated.setBounds(220, 110, 150, 25);

        jLabel1.setText("Espacios disponibles");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 120, 20);

        jLabel2.setText("Carro:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 40, 20);

        jLabel3.setText("Moto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 40, 20);

        jLabel4.setText("Bicicleta:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 55, 20);

        CarsSpace.setText("-");
        getContentPane().add(CarsSpace);
        CarsSpace.setBounds(80, 50, 40, 20);

        MotorcyclesSpace.setText("-");
        getContentPane().add(MotorcyclesSpace);
        MotorcyclesSpace.setBounds(80, 80, 40, 20);

        BikesSpace.setText("-");
        getContentPane().add(BikesSpace);
        BikesSpace.setBounds(80, 110, 40, 20);

        jButton3.setText("Actualizar espacios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 160, 150, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    VehicleInside enterVehicleInterface = new VehicleInside();
    enterVehicleInterface.setVisible(true);
    enterVehicleInterface.txt1.setVisible(false);
    enterVehicleInterface.txt2.setVisible(false);
    enterVehicleInterface.PlateField.setVisible(false);
    enterVehicleInterface.ButtonIn.setEnabled(false);
    this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    VehicleOut VehicleOutInterface = new VehicleOut(); 
    VehicleOutInterface.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void consolidatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consolidatedActionPerformed
    Consolidated newTable = new Consolidated();
    newTable.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_consolidatedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CarsSpace.setText(Integer.toString(Parking1.CarCapacity));
        MotorcyclesSpace.setText(Integer.toString(Parking1.MotorcycleCapacity));
        BikesSpace.setText(Integer.toString(Parking1.BikeCapacity)); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BikesSpace;
    private javax.swing.JLabel CarsSpace;
    private javax.swing.JLabel MotorcyclesSpace;
    private javax.swing.JButton consolidated;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
