/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.pkg3;

import javax.swing.JOptionPane;

/**
 *
 * @author kjuan
 */
public class ParkingParameters extends javax.swing.JFrame {
    int c=0, p=0;  //automatico o defecto
    static int n=1; // se importa para inicializar en 0 , reasigna 1 
    static Parking Parking1;
    /**
     * Creates new form ParkingParameters
     */
    public ParkingParameters() {
        initComponents();
        CarCapacity.setEnabled(false);
        MotorcycleCapacity.setEnabled(false);
        BikeCapacity.setEnabled(false);
        CarPrice.setEnabled(false);
        MotorcyclePrice.setEnabled(false);
        BikePrice.setEnabled(false);
        NigthPrice.setEnabled(false);
        TenHours.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capacity = new javax.swing.ButtonGroup();
        prices = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        defaultCapacity = new javax.swing.JRadioButton();
        costomCapacity = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        defaultPrices = new javax.swing.JRadioButton();
        customPrices = new javax.swing.JRadioButton();
        Buttonacept = new javax.swing.JButton();
        CarCapacity = new javax.swing.JTextField();
        MotorcycleCapacity = new javax.swing.JTextField();
        BikeCapacity = new javax.swing.JTextField();
        CarPrice = new javax.swing.JTextField();
        MotorcyclePrice = new javax.swing.JTextField();
        BikePrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NigthPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TenHours = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(330, 470));
        setMinimumSize(new java.awt.Dimension(330, 470));
        setPreferredSize(new java.awt.Dimension(330, 470));
        getContentPane().setLayout(null);

        jLabel1.setText("Capacidad de parqueadero : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 200, 20);

        capacity.add(defaultCapacity);
        defaultCapacity.setText("Por defecto");
        defaultCapacity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaultCapacityMouseClicked(evt);
            }
        });
        defaultCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultCapacityActionPerformed(evt);
            }
        });
        getContentPane().add(defaultCapacity);
        defaultCapacity.setBounds(40, 50, 100, 25);

        capacity.add(costomCapacity);
        costomCapacity.setText("Personalizado");
        costomCapacity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                costomCapacityMouseClicked(evt);
            }
        });
        getContentPane().add(costomCapacity);
        costomCapacity.setBounds(40, 90, 100, 25);

        jLabel3.setText("Precios : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 200, 20);

        prices.add(defaultPrices);
        defaultPrices.setText("Por defecto");
        defaultPrices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defaultPricesMouseClicked(evt);
            }
        });
        defaultPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultPricesActionPerformed(evt);
            }
        });
        getContentPane().add(defaultPrices);
        defaultPrices.setBounds(40, 200, 100, 25);

        prices.add(customPrices);
        customPrices.setText("Personalizado");
        customPrices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customPricesMouseClicked(evt);
            }
        });
        getContentPane().add(customPrices);
        customPrices.setBounds(40, 240, 100, 25);

        Buttonacept.setText("Aceptar");
        Buttonacept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonaceptActionPerformed(evt);
            }
        });
        getContentPane().add(Buttonacept);
        Buttonacept.setBounds(210, 385, 80, 25);

        CarCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarCapacityActionPerformed(evt);
            }
        });
        getContentPane().add(CarCapacity);
        CarCapacity.setBounds(230, 48, 60, 24);
        getContentPane().add(MotorcycleCapacity);
        MotorcycleCapacity.setBounds(230, 83, 60, 24);
        getContentPane().add(BikeCapacity);
        BikeCapacity.setBounds(230, 118, 60, 24);
        getContentPane().add(CarPrice);
        CarPrice.setBounds(230, 193, 60, 24);
        getContentPane().add(MotorcyclePrice);
        MotorcyclePrice.setBounds(230, 228, 60, 24);
        getContentPane().add(BikePrice);
        BikePrice.setBounds(230, 263, 60, 24);

        jLabel2.setText("Carro");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 50, 50, 20);

        jLabel4.setText("Moto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 85, 50, 20);

        jLabel5.setText("Bicicleta");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 120, 50, 20);

        jLabel6.setText("Carro");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 195, 60, 20);

        jLabel7.setText("Moto");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 230, 60, 20);

        jLabel8.setText("Bicicleta");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 265, 60, 20);

        NigthPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NigthPriceActionPerformed(evt);
            }
        });
        getContentPane().add(NigthPrice);
        NigthPrice.setBounds(230, 298, 60, 24);

        jLabel9.setText("Recargo nocturno");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 300, 110, 20);
        getContentPane().add(TenHours);
        TenHours.setBounds(230, 333, 60, 24);

        jLabel10.setText("+10 horas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 335, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonaceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonaceptActionPerformed
    int CVector[]=new int[3]; //carro moto cicla
    int PVector[]=new int[5]; // precios
    boolean Check1=false; // si no esta completo manda ventana emergente
    boolean Check2=false;
    switch(c){
        case 1:
            CVector[0]=12;
            CVector[1]=8;
            CVector[2]=6;
            Check1=true;
            break;
        case 2:
            if((CarCapacity.getText().equals(""))||(MotorcycleCapacity.getText().equals(""))||(BikeCapacity.getText().equals(""))){
                Check1=false; // ventana emergente por check1 
                break;
            }
            CVector[0]=Integer.parseInt(CarCapacity.getText());
            CVector[1]=Integer.parseInt(MotorcycleCapacity.getText());
            CVector[2]=Integer.parseInt(BikeCapacity.getText());
            Check1=true;
            break;
        default:
            Check1=false;
            break;
    }
    switch(p){
        case 1:
            PVector[0]=75;
            PVector[1]=20;
            PVector[2]=10;
            PVector[3]=5;
            PVector[4]=13000;
            Check2=true;
            break;
        case 2:
            if((CarPrice.getText().equals(""))||(MotorcyclePrice.getText().equals(""))||
                    (BikePrice.getText().equals(""))||(NigthPrice.getText().equals(""))||(TenHours.getText().equals(""))){
            Check2=false;
            break;
            }
            PVector[0]=Integer.parseInt(CarPrice.getText());
            PVector[1]=Integer.parseInt(MotorcyclePrice.getText());
            PVector[2]=Integer.parseInt(BikePrice.getText());
            PVector[3]=Integer.parseInt(NigthPrice.getText());
            PVector[4]=Integer.parseInt(TenHours.getText());
            Check2=true;
            break;
        default:
            Check2=false;
            break;
    }
    if((Check1==true) && (Check2==true)){
        ParkingInterface openParking = new ParkingInterface();
        openParking.setVisible(true);
        this.setVisible(false);
        Parking1 = new Parking(CVector[0],CVector[1],CVector[2],PVector[0],PVector[1],PVector[2],PVector[3],PVector[4]);
    }
    else
        JOptionPane.showMessageDialog(null, "Escoja una opción y/o rellene todas las casillas");
    }//GEN-LAST:event_ButtonaceptActionPerformed

    private void defaultPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultPricesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultPricesActionPerformed

    private void defaultCapacityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultCapacityMouseClicked
        c=1;
        CarCapacity.setEnabled(false);
        MotorcycleCapacity.setEnabled(false);
        BikeCapacity.setEnabled(false);
    }//GEN-LAST:event_defaultCapacityMouseClicked

    private void costomCapacityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_costomCapacityMouseClicked
       c=2;
       CarCapacity.setEnabled(true);
       MotorcycleCapacity.setEnabled(true);
       BikeCapacity.setEnabled(true);
    }//GEN-LAST:event_costomCapacityMouseClicked

    private void defaultPricesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defaultPricesMouseClicked
        p=1;
        CarPrice.setEnabled(false);
        MotorcyclePrice.setEnabled(false);
        BikePrice.setEnabled(false);
        NigthPrice.setEnabled(false);
        TenHours.setEnabled(false);
    }//GEN-LAST:event_defaultPricesMouseClicked

    private void customPricesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customPricesMouseClicked
        p=2;
        CarPrice.setEnabled(true);
        MotorcyclePrice.setEnabled(true);
        BikePrice.setEnabled(true);
        NigthPrice.setEnabled(true);
        TenHours.setEnabled(true);
    }//GEN-LAST:event_customPricesMouseClicked

    private void CarCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarCapacityActionPerformed

    private void NigthPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NigthPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NigthPriceActionPerformed

    private void defaultCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultCapacityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingParameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingParameters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BikeCapacity;
    private javax.swing.JTextField BikePrice;
    private javax.swing.JButton Buttonacept;
    private javax.swing.JTextField CarCapacity;
    private javax.swing.JTextField CarPrice;
    private javax.swing.JTextField MotorcycleCapacity;
    private javax.swing.JTextField MotorcyclePrice;
    private javax.swing.JTextField NigthPrice;
    private javax.swing.JTextField TenHours;
    private javax.swing.ButtonGroup capacity;
    private javax.swing.JRadioButton costomCapacity;
    private javax.swing.JRadioButton customPrices;
    private javax.swing.JRadioButton defaultCapacity;
    private javax.swing.JRadioButton defaultPrices;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup prices;
    // End of variables declaration//GEN-END:variables

    private void swicth(int c) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void swicht(int c) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
