/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.pkg3;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import static laboratorio.pkg3.ParkingParameters.n;
import static laboratorio.pkg3.ParkingParameters.Parking1;

/**
 *
 * @author User
 */
public class VehicleInside extends javax.swing.JFrame {
    static Vehicle Vehicles = new Vehicle();
    /**
     * Creates new form ParkingParameters
     */
        
    public VehicleInside() {
        
        initComponents();
        ButtonIn.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectTime = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        ButtonIn = new javax.swing.JButton();
        txt1 = new javax.swing.JLabel();
        PlateField = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        Buttonreturn = new javax.swing.JButton();
        LabelBike = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(315, 240));
        setMinimumSize(new java.awt.Dimension(315, 240));
        setPreferredSize(new java.awt.Dimension(315, 240));
        getContentPane().setLayout(null);

        jLabel3.setText("Tipo de vehiculo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 100, 20);

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Carro", "Moto", "Bicicleta" }));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Type);
        Type.setBounds(150, 20, 106, 25);

        ButtonIn.setText("ENTRAR");
        ButtonIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonIn);
        ButtonIn.setBounds(180, 150, 80, 25);

        txt1.setText("Placa :");
        getContentPane().add(txt1);
        txt1.setBounds(80, 60, 50, 20);

        PlateField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PlateFieldComponentShown(evt);
            }
        });
        PlateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PlateField);
        PlateField.setBounds(150, 58, 106, 25);

        txt2.setText("Bicicleta n° :");
        getContentPane().add(txt2);
        txt2.setBounds(65, 100, 70, 20);

        Buttonreturn.setText("Volver");
        Buttonreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonreturnActionPerformed(evt);
            }
        });
        getContentPane().add(Buttonreturn);
        Buttonreturn.setBounds(30, 150, 80, 25);
        getContentPane().add(LabelBike);
        LabelBike.setBounds(150, 100, 106, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        String valor; //coloca el numero a unavariable
        valor = (String)Type.getSelectedItem();
            if (valor.equals("-"))
        {
            txt1.setVisible(false);
            txt2.setVisible(false);
            LabelBike.setVisible(false);
            PlateField.setVisible(false);
            ButtonIn.setEnabled(false);
        }
            else 
            {
                if(valor.equals("Carro")||valor.equals("Moto"))
                {
                    PlateField.setVisible(true);
                    txt1.setVisible(true);
                    txt2.setVisible(false);
                    LabelBike.setVisible(false);
                    ButtonIn.setEnabled(true);
                }
                else
                    if(valor.equals("Bicicleta"))
                    {
                        txt1.setVisible(false);
                        txt2.setVisible(true);
                        LabelBike.setVisible(true);
                        PlateField.setVisible(false);
                        ButtonIn.setEnabled(true);
                        LabelBike.setText("" + n);
                    }
                
            }
    }//GEN-LAST:event_TypeActionPerformed

    private void PlateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateFieldActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_PlateFieldActionPerformed

    private void PlateFieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PlateFieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateFieldComponentShown

    private void ButtonInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInActionPerformed

        if((PlateField.getText().length()==0)&&(Type.getSelectedItem().equals("Moto")||Type.getSelectedItem().equals("Carro"))){
            JOptionPane.showMessageDialog(null, "Rellene todas las casillas");
        }
        else{
            String PlateOrNum = null;
            if (Type.getSelectedItem().equals("Bicicleta")){
                PlateOrNum=LabelBike.getText();
                n=n+1;
                Parking1.BikeCapacity=Parking1.BikeCapacity-1;
            }
            else if (Type.getSelectedItem().equals("Moto")){
                Parking1.MotorcycleCapacity=Parking1.MotorcycleCapacity-1;
                PlateOrNum=PlateField.getText();
            }
            else if (Type.getSelectedItem().equals("Carro")){
                Parking1.CarCapacity=Parking1.CarCapacity-1;
                PlateOrNum=PlateField.getText();
            }
            Vehicles.AddVehicle((String)Type.getSelectedItem(), PlateOrNum, LocalDateTime.now());
            //obj.Nose((String)Type.getSelectedItem(), PlateOrNum, LocalDateTime.now());
            ParkingInterface Return = new ParkingInterface();
            Return.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_ButtonInActionPerformed

    private void ButtonreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonreturnActionPerformed
        ParkingInterface Return = new ParkingInterface();
        Return.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ButtonreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleInside().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonIn;
    private javax.swing.JButton Buttonreturn;
    private javax.swing.JLabel LabelBike;
    public javax.swing.JTextField PlateField;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JLabel jLabel3;
    private javax.swing.ButtonGroup selectTime;
    public javax.swing.JLabel txt1;
    public javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
