/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.pkg3;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class VehicleInside extends javax.swing.JFrame {
    int n=0;
    static Vehicle Vehicles = new Vehicle();
    /**
     * Creates new form ParkingParameters
     */
    public VehicleInside() {
        initComponents();
        ButtonIn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectTime = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        Type = new javax.swing.JComboBox<>();
        ButtonIn = new javax.swing.JButton();
        txt1 = new javax.swing.JLabel();
        PlateField = new javax.swing.JTextField();
        txt2 = new javax.swing.JLabel();
        Buttonreturn = new javax.swing.JButton();
        LabelBike = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Tipo de vehiculo");

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Carro", "Moto", "Bicicleta" }));
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });

        ButtonIn.setText("ENTRAR");
        ButtonIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInActionPerformed(evt);
            }
        });

        txt1.setText("Placa :");

        PlateField.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PlateFieldComponentShown(evt);
            }
        });
        PlateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateFieldActionPerformed(evt);
            }
        });

        txt2.setText("Bicicleta n° :");

        Buttonreturn.setText("Volver");
        Buttonreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonreturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Buttonreturn)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonIn)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt2)
                            .addComponent(txt1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(PlateField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelBike, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIn)
                    .addComponent(Buttonreturn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1)
                    .addComponent(PlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt2)
                    .addComponent(LabelBike, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        String valor; //coloca el numero a unavariable
        valor = (String)Type.getSelectedItem();
            if (valor.equals("-"))
        {
            txt1.setVisible(false);
            txt2.setVisible(false);
            LabelBike.setVisible(false);
            PlateField.setVisible(false);
            ButtonIn.setEnabled(false);
        }
            else 
            {
                if(valor.equals("Carro")||valor.equals("Moto"))
                {
                    PlateField.setVisible(true);
                    txt1.setVisible(true);
                    txt2.setVisible(false);
                    LabelBike.setVisible(false);
                    ButtonIn.setEnabled(true);
                }
                else
                    if(valor.equals("Bicicleta"))
                    {
                        txt1.setVisible(false);
                        txt2.setVisible(true);
                        LabelBike.setVisible(true);
                        PlateField.setVisible(false);
                        ButtonIn.setEnabled(true);
                        n=n+1;
                        LabelBike.setText("" + n);
                    }
                
            }
    }//GEN-LAST:event_TypeActionPerformed

    private void PlateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateFieldActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_PlateFieldActionPerformed

    private void PlateFieldComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PlateFieldComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateFieldComponentShown

    private void ButtonInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInActionPerformed
        if((PlateField.getText().length()==0)&&(Type.getSelectedItem().equals("Moto")||Type.getSelectedItem().equals("Carro"))){
            JOptionPane.showMessageDialog(null, "Rellene todas las casillas");
        }
        else{
            String PlateOrNum;
            if (Type.getSelectedItem().equals("Bicicleta"))
                PlateOrNum=LabelBike.getText();
            else
                PlateOrNum=PlateField.getText();
            Vehicles.AddVehicle((String)Type.getSelectedItem(), PlateOrNum, LocalDateTime.now());
            ParkingInterface Return = new ParkingInterface();
            Return.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_ButtonInActionPerformed

    private void ButtonreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonreturnActionPerformed
        ParkingInterface Return = new ParkingInterface();
        Return.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ButtonreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleInside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleInside().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ButtonIn;
    private javax.swing.JButton Buttonreturn;
    private javax.swing.JLabel LabelBike;
    public javax.swing.JTextField PlateField;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JLabel jLabel3;
    private javax.swing.ButtonGroup selectTime;
    public javax.swing.JLabel txt1;
    public javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
