/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio.pkg3;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import static laboratorio.pkg3.VehicleInside.Vehicles;
import static laboratorio.pkg3.ParkingParameters.Parking1;
/**
 *
 * @author kjuan
 */
public class VehicleOut extends javax.swing.JFrame {

    /**
     * Creates new form VehicleOut
     */
    public VehicleOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departureTime = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        PlateLabel = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(320, 160));
        setMinimumSize(new java.awt.Dimension(320, 160));
        setPreferredSize(new java.awt.Dimension(320, 160));
        getContentPane().setLayout(null);

        jLabel2.setText("Ingrese placa o numero :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 130, 25);

        PlateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateLabelActionPerformed(evt);
            }
        });
        getContentPane().add(PlateLabel);
        PlateLabel.setBounds(170, 20, 100, 25);

        returnButton.setText("Volver");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton);
        returnButton.setBounds(25, 70, 100, 25);

        ExitButton.setText("Confirmar salida");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(145, 70, 140, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlateLabelActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
    ParkingInterface returnEnd = new ParkingInterface();
    returnEnd.setVisible(true);
    this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_returnButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    String Plate=PlateLabel.getText();
    if(Plate.length()==0){
        JOptionPane.showMessageDialog(null, "Rellene todas las casillas");
        }
    else{
        int Value=0;
        switch (Vehicles.GetType(Plate)) {
            case "Carro":
                Value=Parking1.CarPrice;
                break;
            case "Moto":
                Value=Parking1.MotorcyclePrice;
                break;
            case "Bicicleta":
                Value=Parking1.BikePrice;
                break;
            default:
                break;
        }
        Vehicles.VehicleOut(Plate, LocalDateTime.now(), Value, Parking1.NigthPrice, Parking1.TenHours);
        ParkingInterface openParking = new ParkingInterface();
        openParking.setVisible(true);
        this.setVisible(false);
    }
            switch (Vehicles.GetType(Plate)) {
            case "Bicicleta":
                Parking1.BikeCapacity=Parking1.BikeCapacity+1;
                break;
            case "Moto":
                Parking1.MotorcycleCapacity=Parking1.MotorcycleCapacity+1;
                break;
            case "Carro":
                Parking1.CarCapacity=Parking1.CarCapacity+1;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField PlateLabel;
    private javax.swing.ButtonGroup departureTime;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
